import Weather from "./page";

export const metadata = {
    title: "Weather App",
    description: "Generated by TPHL1611",
};

export default function WeatherLayout({ children }) {
    return <Weather />;
}
