import Pomodoro from "./page";

export const metadata = {
    title: "Pomodoro App",
    description: "Generated by TPHL1611",
};

export default function PomodoroLayout({ children }) {
    return <Pomodoro />;
}
